//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_BIBLIOTECA_CarlosMurilloGomez
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_bibliotecaEntities : DbContext
    {
        public bd_bibliotecaEntities()
            : base("name=bd_bibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GENEROS> GENEROS { get; set; }
        public virtual DbSet<LIBROS> LIBROS { get; set; }
        public virtual DbSet<PRESTAMOS> PRESTAMOS { get; set; }
        public virtual DbSet<SOCIOS> SOCIOS { get; set; }
    }
}
