//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SG_BIBLIOTECA_CarlosMurilloGomez
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMOS
    {
        public int Id_prestamo { get; set; }
        public string Socio { get; set; }
        public int Libro { get; set; }
        public System.DateTime Fecha_prestamo { get; set; }
        public Nullable<System.DateTime> Fecha_devolucion { get; set; }
    
        public virtual LIBROS LIBROS { get; set; }
        public virtual SOCIOS SOCIOS { get; set; }
    }
}
